'use strict';
(function () {
    const availableCountries = [ // order by most repeated
        'usa',
        'germany',
        'france',
        'canada',
        'russia',
        'uk',
        'australia',
        'sweden',
        'poland',
        'india',
        'brazil',
        'spain',
        'ukraine',
        'netherlands',
        'italy',
        'belgium',
        'denmark',
        'norway',
        'mexico',
        'argentina',
        'finland',
        'czechrepublic',
        'switzerland',
        'southafrica',
        'romania',
        'newzealand',
        'portugal',
        'austria',
        'israel',
        'colombia',
        'ireland',
        'indonesia',
        'belarus',
        'hungary',
        'philippines',
        'turkey',
        'greece',
        'bulgaria',
        'serbia',
        'singapore',
        'china',
        'japan',
        'nigeria',
        'croatia',
        'estonia',
        'chile',
        'iran',
        'malaysia',
        'egypt',
        'slovakia',
        'taiwan',
        'uruguay',
        'lithuania',
        'pakistan',
        'slovenia',
        'peru',
        'vietnam',
        'venezuela',
        'latvia',
        'moldova',
        'costarica',
        'thailand',
        'bangladesh',
        'bolivia',
        'southkorea',
        'morocco',
        'dominicanrepublic',
        'nepal',
        'kenya',
        'iceland',
        'ecuador',
        'malta',
        'macedonia',
        'tunisia',
        'kazakhstan',
        'bosniaandherzegovina',
        'luxembourg',
        'ghana',
        'lebanon',
        'paraguay',
        'unitedarabemirates',
        'panama',
        'elsalvador',
        'puertorico',
        'cameroon',
        'cyprus',
        'zambia',
        'armenia',
        'honduras',
        'srilanka',
        'georgia',
        'guatemala',
        'ethiopia',
        'algeria',
        'kosovo',
        'trinidadandtobago',
        'zimbabwe',
        'jordan',
        'nicaragua',
        'saudiarabia',
        'cambodia',
        'kyrgyzstan',
        'uzbekistan',
        'barbados',
        'mauritius',
        'senegal',
        'syria',
        'cuba',
        'uganda',
        'tanzania',
        'palestine',
        'albania',
        'myanmar',
        'haiti',
        'iraq',
        'mongolia',
        'sudan',
        'montenegro',
        'azerbaijan',
        'liechtenstein',
        'ivorycoast',
        'madagascar',
    ];

    const manualMapping = { // order by most repeated
        'unitedstates': 'usa',
        'us': 'usa',
        'unitedkingdom': 'uk',
        'unitedstatesofamerica': 'usa',
        'thenetherlands': 'netherlands',
        'england': 'uk',
        'czechia': 'czechrepublic',
        'brasil': 'brazil',
        'russianfederation': 'russia',
        'hongkong': 'china',
        'scotland': 'uk',
        'korea': 'southkorea',
        'nl': 'netherlands',
        'de': 'germany',
        'cz': 'czechrepublic',
        'catalonia': 'spain',
        'northernireland': 'uk',
        'america': 'usa',
        'fr': 'france',
        'nz': 'newzealand',
        'republicofkorea': 'southkorea',
        'merica': 'usa',
        'unitedstate': 'usa',
        'republicofmoldova': 'moldova',
        'ru': 'russia',
        'uae': 'unitedarabemirates',
        'bosniaherzegovina': 'bosniaandherzegovina',
        'czech': 'czechrepublic',
        'basquecountry': 'spain',
        'greatbritain': 'uk',
        'murica': 'usa',
        'au': 'australia',
        'za': 'southafrica',
        'netherland': 'netherlands',
        'aus': 'australia',
        'ukrain': 'ukraine',
        'usofa': 'usa',
        'it': 'italy',
        'theczechrepublic': 'czechrepublic',
        'ua': 'ukraine',
        'walesuk': 'uk',
        'isreal': 'israel',
        'at': 'austria',
        'pl': 'poland',
        'guernsey': 'uk',
        'gb': 'uk',
        'russian': 'russia',
        'unitedstateofamerica': 'usa',
        'motherrussia': 'russia',
        'ch': 'china',
        'polska': 'poland',
        'espana': 'spain',
        'ger': 'germany',
        'french': 'france',
        'unitedstated': 'usa',
        'wales': 'uk',
        'beijing': 'china',
        'swizterland': 'switzerland',
        'morroco': 'morocco',
        'theunitedkingdom': 'uk',
        'es': 'spain',
        'syberia': 'russia',
        'untiedstates': 'usa',
        'southofkorea': 'southkorea',
        'catalunya': 'spain',
        'britain': 'uk',
        'gernany': 'germany',
        'newzeland': 'newzealand',
        'switzlerand': 'switzerland',
        'theneterlands': 'netherlands',
        'getmany': 'germany',
        'gbr': 'uk',
        'englanduk': 'uk',
        'bosniahercegowina': 'bosniaandherzegovina',
        'unitedkingom': 'uk',
        'unitesstates': 'usa',
        'irealand': 'ireland',
        'unitedkindgom': 'uk',
        'unitedkindom': 'uk',
        'italia': 'italy',
        'german': 'germany',
        'switzerlandwhyisthisafreetextfieldthiswillbeapainintheassforthepoorsodwhohastonormalisethis': 'switzerland', // I take this one into account for obvious reasons
    };

    const normalizeCountryByISOCode = {
        100: "bulgaria",
        104: "myanmar",
        112: "belarus",
        116: "cambodia",
        120: "cameroon",
        124: "canada",
        144: "srilanka",
        152: "chile",
        156: "china",
        170: "colombia",
        188: "costarica",
        191: "croatia",
        192: "cuba",
        196: "cyprus",
        203: "czechrepublic",
        208: "denmark",
        214: "dominicanrepublic",
        218: "ecuador",
        222: "elsalvador",
        231: "ethiopia",
        233: "estonia",
        246: "finland",
        250: "france",
        268: "georgia",
        276: "germany",
        288: "ghana",
        300: "greece",
        320: "guatemala",
        332: "haiti",
        340: "honduras",
        344: "china",
        348: "hungary",
        352: "iceland",
        356: "india",
        360: "indonesia",
        368: "iraq",
        372: "ireland",
        376: "israel",
        380: "italy",
        392: "japan",
        398: "kazakhstan",
        400: "jordan",
        404: "kenya",
        417: "kyrgyzstan",
        422: "lebanon",
        428: "latvia",
        438: "liechtenstein",
        440: "lithuania",
        442: "luxembourg",
        450: "madagascar",
        458: "malaysia",
        470: "malta",
        480: "mauritius",
        484: "mexico",
        496: "mongolia",
        499: "montenegro",
        504: "morocco",
        524: "nepal",
        528: "netherlands",
        554: "newzealand",
        558: "nicaragua",
        566: "nigeria",
        578: "norway",
        586: "pakistan",
        591: "panama",
        600: "paraguay",
        604: "peru",
        608: "philippines",
        616: "poland",
        620: "portugal",
        630: "puertorico",
        642: "romania",
        643: "russia",
        682: "saudiarabia",
        686: "senegal",
        688: "serbia",
        702: "singapore",
        703: "slovakia",
        704: "vietnam",
        705: "slovenia",
        710: "southafrica",
        716: "zimbabwe",
        724: "spain",
        729: "sudan",
        752: "sweden",
        756: "switzerland",
        764: "thailand",
        780: "trinidadandtobago",
        784: "unitedarabemirates",
        788: "tunisia",
        792: "turkey",
        800: "uganda",
        804: "ukraine",
        818: "egypt",
        831: "uk",
        840: "usa",
        858: "uruguay",
        860: "uzbekistan",
        894: "zambia",
        8: "albania",
        12: "algeria",
        31: "azerbaijan",
        32: "argentina",
        36: "australia",
        40: "austria",
        50: "bangladesh",
        51: "armenia",
        52: "barbados",
        56: "belgium",
        70: "bosniaandherzegovina",
        76: "brazil",
        158: "taiwan",
        275: "palestine",
        410: "southkorea",
        498: "moldova",
        807: "macedonia",
        826: "uk",
        834: "tanzania",
        862: "venezuela",
        364: "iran",
        68: "bolivia",
        760: "syria",
        // "ivorycoast", there is no country code
        // "kosovo", there is no country code for kosovo
    };

    function normalizeCountry(country) {
        const normalize = _.deburr(country)
            .toLowerCase()
            .replace(/[^a-z]/g, '');
        return availableCountries.includes(normalize)
            ? normalize
            : manualMapping[normalize] || null;
    }

    window.normalizeCountry = normalizeCountry;
    window.normalizeCountryByISOCode = normalizeCountryByISOCode;
})();